config/routes.rb
GuitarWorkshop::Application.routes.draw do

  match "/login" => "UserSessions#new"
  match "/logout" => "UserSessions#destroy"
  match "/show_order_info" => "Home#show_order_info"
  match "/admin" => "Admins#index"
  match "/forgot_password" => "PasswordResets#new"
  resources :user_sessions
  resources :parts
  resources :services
  resources :users
  resources :orders
  resources :password_resets

  root :to => "Home#index"

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  before_filter :require_no_user, :only => [:show_order_info]

  respond_to :html

  def index

  end

  def show_order_info
    redirect_to root_path and return unless request.post? or params[:order]
    @order = Order.find_by_code(params[:order][:code])
    if @order
      render :template => "/home/show_order" and return
    else
      flash[:notice] = t "orders.not_found"
      render :index
    end
  end

end

app/views/home/index.html.haml
= notice
= simple_form_for :order, :url => show_order_info_path do |f|
  = f.input :code
  = f.button :submit

app/views/home/show_order.html.haml
%div.info.order_info
  %div
    %span.label= t "orders.manager"
    = @order.manager.name
  -if @order.manager.phone
    %div
      %span.label= t "orders.manager_phone"
      = @order.manager.phone
  %div
    %span.label= t "orders.manager_email"
    = link_to @order.manager.email, "mailto:@order.manager.email"
  %div
    %span.label= t "common.description"
    = @order.description
  %div
    %span.label= t "orders.status"
    = order_status(@order)
  %div
    %span.label= t "orders.complete_at"
    = format_date(@order.completed_at)
  %div
    %span.label= t "orders.paid"
    = format_flag @order.paid
%div.orderlines.tbl
  %table
    %tr.header
      %th= t "services.long_name"
      %th= t "services.quantity"
      %th= t "orders.orderline.service_price"
      %th= t "orders.orderline.parts_price"
      %th= t "common.price"
      %th= t("orders.orderline.status")
    - @order.orderlines.each do |orderline|
      %tr
        %td= orderline.service.name
        %td.number= orderline.count
        %td.number= format_price orderline.service_total
        %td.number= format_price orderline.parts_total
        %td.number= format_price orderline.total
        %td.center= format_flag orderline.done
    %tr
      %td{ :colspan => 4 }
        = t "common.total"
      %td{ :colspan => 2, :class => "number" }
        = format_price @order.total
= item_actions @order
= link_to_history_back