config/routes.rb
GuitarWorkshop::Application.routes.draw do

  match "/login" => "UserSessions#new"
  match "/logout" => "UserSessions#destroy"
  match "/show_order_info" => "Home#show_order_info"
  match "/admin" => "Admins#index"
  match "/forgot_password" => "PasswordResets#new"
  resources :user_sessions
  resources :parts
  resources :services
  resources :users
  resources :orders
  resources :password_resets

  root :to => "Home#index"

end

app/views/common/_admin_navigation.html.haml
=nav link_to_unless_current t("navigation.orders"), orders_path
=nav link_to_unless_current t("navigation.parts"), parts_path
=nav link_to_unless_current t("navigation.services"), services_path
=nav link_to_unless_current t("navigation.administration"), admin_path

app/views/common/_client_navigation.html.haml
=nav link_to_unless_current t("navigation.home"), root_path
=nav link_to_unless_current t("navigation.parts"), parts_path
=nav link_to_unless_current t("navigation.services"), services_path

app/views/common/_error_messages.html.haml
%div#error_explanation
  %h2= t "common.error"
  %ul
  - object.errors.full_messages.each do |msg|
    %li
      = msg

app/views/common/_login_bar.html.haml
- unless current_user
  = link_to t("login_bar.login"), login_path
  = link_to t("login_bar.forgot_password"), forgot_password_path
- else
  = link_to t("login_bar.logged_in_as", :username => current_user.name)
  = link_to t("login_bar.logout"), logout_path

app/views/common/_manager_navigation.html.haml
=nav link_to_unless_current t("navigation.orders"), orders_path
=nav link_to_unless_current t("navigation.parts"), parts_path
=nav link_to_unless_current t("navigation.services"), services_path